services:
    db:
        container_name: virtuoso-db
        image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "https://www.dalicc.net/ld"
        volumes:
            - ./virtuoso_data:/data
        ports:
            - "8890:8890"
    api:
        container_name: dalicc-api
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8002:80"
        volumes:
            - .:/app
        entrypoint: ['/start-reload.sh']
    reasoner:
        container_name: dalicc-reasoner
        build:
            context: ./reasoner/
            dockerfile: Dockerfile
        ports:
            - "8190:80"
        volumes:
            - ./reasoner:/app
        entrypoint: ['/start-reload.sh']
    db_wp:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: <root_password>
            MYSQL_DATABASE: <db_name>
            MYSQL_USER: <db_user>
            MYSQL_PASSWORD: <db_password>
    
    wordpress:
        depends_on:
            - db_wp
        image: wordpress:latest
        volumes:
            - wordpress_data:/var/www/html
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db_wp:<wp_db_port>
            WORDPRESS_DB_USER: <db_user>
            WORDPRESS_DB_PASSWORD: <db_password>
            WORDPRESS_DB_NAME: <db_name>
volumes:
  db_data: {}
  wordpress_data: {}
