services:
    db:
        container_name: virtuoso-db
        image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "https://www.dalicc.net/ld"
        volumes:
            - ./virtuoso_data:/data
        ports:
            - "8890:8890"
    api:
        container_name: dalicc-api
        #environment:
        #    APP_MODULE: "--proxy-headers"
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8002:80"
        volumes:
            - .:/app
        entrypoint: ['/start-reload.sh']
        environment:
            - DB_URL=http://virtuoso-db:8890/sparql
            - REASONER_URL=http://dalicc-reasoner:80/reasoner
    reasoner:
        container_name: dalicc-reasoner
        build:
            context: ./reasoner/
            dockerfile: Dockerfile
        ports:
            - "8190:80"
        volumes:
            - ./reasoner:/app
        entrypoint: ['/start-reload.sh']
        environment:
            - DB_URL=http://virtuoso-db:8890/sparql
    db_wp:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
    
    wordpress:
        depends_on:
            - db_wp
        image: wordpress:latest
        volumes:
            - wordpress_data:/var/www/html
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db_wp:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}
